from .category import CategoryList,CategoryDetail
from .contact import ContactList,ContactDetail
from .school import SchoolList,SchoolDetail,SchoolSearchByAddress,HSchoolSearchByCategory,SchoolSearchByName